buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.4.2"
    }
}

apply plugin: "com.android.application"
apply plugin: "kotlin-android"

android {
    namespace "com.mgo.driverpro"
    compileSdk 33
    defaultConfig {
        applicationId "com.mgo.driverpro"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation "androidx.core:core-ktx:1.9.0"
}