plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
}

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.mxl.driverpro'
    compileSdk 34
    defaultConfig {
        applicationId "com.mxl.driverpro"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10'
    implementation platform('com.google.firebase:firebase-bom:32.7.0')
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-messaging'
}
