apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.mxl.driverpro'
    compileSdk 34
    
    defaultConfig {
        applicationId "com.mxl.driverpro"
        minSdk 24
        targetSdk 34
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
}
